# Generated by Django 4.1.3 on 2023-01-12 15:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('paymentapp', '0003_remove_wallet_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transfer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('wallet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='paymentapp.wallet')),
            ],
        ),
    ]
